### ISSUE TITLE
Expose the Freebase Domain/Type hierarchy

### ISSUE THREAD

**Issue by thadguidry** [Tpt/freebase-browser#2]
Example:
https://tools.wmflabs.org/freebase/m/04lcnlf

Expected to see somewhere the original Domain Type or perhaps the Type's original "url":
"id": "/m/04lcnlf",
"type": "/government/political_party",
"url": "https://www.freebase.com/government/political_party"

![Annotation 2019-09-28 090032](https://user-images.githubusercontent.com/986438/65817588-c79d5400-e1ce-11e9-8746-f9469e5669f2.png)

**Comment by thadguidry** [comment]
@Tpt would it help if I fill in the Class mapping here: https://www.wikidata.org/wiki/Wikidata:WikiProject_Freebase/Class_mapping  ??
Or can you walk the relations in the Freebase dump to get the Domain Types (which you should be able to do, btw) ?

**Comment by Tpt** [comment]
I built this tool by reading the Freebase dump. I should definitely be able to get the domain type indeed. I also plan to extract domain/range/inverse property facts.

**Comment by Tpt** [comment]
There was indeed some problems with the text ids. It should be fixed now.

For example, for [/people/person/gender](https://tools.wmflabs.org/freebase/people/person/gender), the text id is properly displayed alongside the label. https://tools.wmflabs.org/freebase/people/person/gender also properly redirects (and same for keys).

I have extracted properties metadata. They should be all displayed.

Feel free to open this task again if there are still issues.

**Comment by thadguidry** [comment]
@Tpt Great, but the Freebase Types are not separated out from the div... that's actually what I need as well...

![Annotation 2019-11-08 082019](https://user-images.githubusercontent.com/986438/68483251-ce24df80-0200-11ea-873f-ac2754e915ec.png)

**Comment by Tpt** [comment]
"Other types" and "Notable types" list all the types encoded by the `/type/object/type` relation.  "Notable types" are the types encoded by `/common/topic/notable_types`. The display use their labels except for `/music/writer` here were the label has not been found. 

Does it answers your question or are you thinking about an other kind of Freebase "type"?

**Comment by thadguidry** [comment]
I did look at your processing code, so I understand what your doing, its just that I was trying to say that not all Types in Freebase were treated equally.  The hierarchy overlay was /Domain/Type/Property.  And its when I say /Domain/Type should be treated as being part of particular Sets.  One in particular was our Commons.  Whenever the /Domain/Type was part of the Commons it was treated special (I don't know how that looks like in the RDF however...my memory is fading.)  Notable was just a flag, in essence.

I'm asking if there is a way to separate the Sets of Types.  (Common, User, etc.) and have the UI represent that better, rather than bucketing all of them into "Other types".

**Comment by thadguidry** [comment]
Better yet... Can you write up a quick SETUP.md document for me that describes what I need to get this running on my system and so I can contribute?  Are you using Oxigraph or PostgreSQL with sqlalchemy? What does the db config look like?  Help me to get setup how you have for parsing, loading, displaying...and then I can contribute in many areas on your tools/repos.
