### ISSUE TITLE
Question: How to get a mid_textid_file?

### ISSUE THREAD

**Issue by jariojose** [Tpt/freebase-browser#6]
Firstly, congratulations on this work! It is amazing!

@Tpt How could I find this dump or how to create it?

Thank you, dear!

**Comment by Tpt** [comment]
Hi! Thank you!

You could just download the last Freebase dump and grep in it "type.object.id".

**Comment by jariojose** [comment]
Nice, dear!!!! So, could I use any relation or Must I use only type.object.id ?

**Comment by Tpt** [comment]
The goal of the file is just having something smaller than the full dump to extract the type.object.id relation (the Python N-Triples paper is very slow). You could have other triples in the file, it won't change anything.

**Comment by jariojose** [comment]
All right, man!

Many thanks!!!
